logging:
  level:
    root: INFO
    org.springframework.boot.context.config: DEBUG
    org.springframework.integration: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.integration.channel: TRACE
    org.springframework.integration.handler: TRACE
    org.springframework.integration.endpoint: TRACE
    org.springframework.integration.router: TRACE
    org.springframework.integration.transformer: TRACE
    org.springframework.integration.gateway: TRACE
    org.springframework.integration.dispatcher: TRACE

server:
  port: 8085

integration:
  flow:
    - from: httpInboundChannel
      to: enricherInput
#    - from: enricherOutput
#      to: transformerInput
#    - from: transformerOutput
#      to: inboxInput
#    - from: inboxOutput
#      to: httpOutboundInput
#    - from: httpOutboundOutput
#      to: serviceInput1
#    - from: serviceOutput1
#      to: responseChannel
#    - from: aggregatorOutput
#      to: responseChannel
    - from: enricherOutput
      to: inboxInput
    - from: inboxOutput
      to: serviceInput1
    - from: serviceOutput1
      to: serviceInput2
    - from: serviceOutput2
      to: responseChannel
  service-activators:
    - bean: myService
      method: print
      args:
        - expression: "#root['name']"
        - expression: "#root['email']"
    - bean: myService
      method: print2
      args:
        - expression: "#root['data']"
        - expression: "#root['source']"
  aggregator:
    input: aggregatorInput
    output: aggregatorOutput